export const CardsData = [
  {
    name: 'Mixmax0',
    budget_name: 'Software subscription',
    owner_id: 0,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax1',
    budget_name: 'Software subscription',
    owner_id: 1,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax2',
    budget_name: 'Software subscription',
    owner_id: 2,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax3',
    budget_name: 'Software subscription',
    owner_id: 3,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax4',
    budget_name: 'Software subscription',
    owner_id: 4,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax5',
    budget_name: 'Software subscription',
    owner_id: 5,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax6',
    budget_name: 'Software subscription',
    owner_id: 6,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax7',
    budget_name: 'Software subscription',
    owner_id: 7,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax8',
    budget_name: 'Software subscription',
    owner_id: 8,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax9',
    budget_name: 'Software subscription',
    owner_id: 9,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax10',
    budget_name: 'Software subscription',
    owner_id: 10,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax11',
    budget_name: 'Software subscription',
    owner_id: 11,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax12',
    budget_name: 'Software subscription',
    owner_id: 12,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax13',
    budget_name: 'Software subscription',
    owner_id: 13,
spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax14',
    budget_name: 'Software subscription',
    owner_id: 14,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax15',
    budget_name: 'Software subscription',
    owner_id: 15,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax16',
    budget_name: 'Software subscription',
    owner_id: 16,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax17',
    budget_name: 'Software subscription',
    owner_id: 17,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax18',
    budget_name: 'Software subscription',
    owner_id: 18,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax19',
    budget_name: 'Software subscription',
    owner_id: 19,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax20',
    budget_name: 'Software subscription',
    owner_id: 20,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax21',
    budget_name: 'Software subscription',
    owner_id: 21,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax22',
    budget_name: 'Software subscription',
    owner_id: 22,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax23',
    budget_name: 'Software subscription',
    owner_id: 23,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax24',
    budget_name: 'Software subscription',
    owner_id: 24,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax25',
    budget_name: 'Software subscription',
    owner_id: 25,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax26',
    budget_name: 'Software subscription',
    owner_id: 26,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax27',
    budget_name: 'Software subscription',
    owner_id: 27,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax28',
    budget_name: 'Software subscription',
    owner_id: 28,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax29',
    budget_name: 'Software subscription',
    owner_id: 29,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax30',
    budget_name: 'Software subscription',
    owner_id: 30,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax31',
    budget_name: 'Software subscription',
    owner_id: 31,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax32',
    budget_name: 'Software subscription',
    owner_id: 32,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax33',
    budget_name: 'Software subscription',
    owner_id: 33,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax34',
    budget_name: 'Software subscription',
    owner_id: 34,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax35',
    budget_name: 'Software subscription',
    owner_id: 35,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax36',
    budget_name: 'Software subscription',
    owner_id: 36,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax37',
    budget_name: 'Software subscription',
    owner_id: 37,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax38',
    budget_name: 'Software subscription',
    owner_id: 38,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax39',
    budget_name: 'Software subscription',
    owner_id: 39,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax40',
    budget_name: 'Software subscription',
    owner_id: 40,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax41',
    budget_name: 'Software subscription',
    owner_id: 41,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax42',
    budget_name: 'Software subscription',
    owner_id: 42,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax43',
    budget_name: 'Software subscription',
    owner_id: 43,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax44',
    budget_name: 'Software subscription',
    owner_id: 44,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax45',
    budget_name: 'Software subscription',
    owner_id: 45,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax46',
    budget_name: 'Software subscription',
    owner_id: 46,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax47',
    budget_name: 'Software subscription',
    owner_id: 47,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax48',
    budget_name: 'Software subscription',
    owner_id: 48,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax49',
    budget_name: 'Software subscription',
    owner_id: 49,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax50',
    budget_name: 'Software subscription',
    owner_id: 50,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax51',
    budget_name: 'Software subscription',
    owner_id: 51,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax52',
    budget_name: 'Software subscription',
    owner_id: 52,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax53',
    budget_name: 'Software subscription',
    owner_id: 53,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax54',
    budget_name: 'Software subscription',
    owner_id: 54,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax55',
    budget_name: 'Software subscription',
    owner_id: 55,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax56',
    budget_name: 'Software subscription',
    owner_id: 56,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax57',
    budget_name: 'Software subscription',
    owner_id: 57,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax58',
    budget_name: 'Software subscription',
    owner_id: 58,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax59',
    budget_name: 'Software subscription',
    owner_id: 59,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax60',
    budget_name: 'Software subscription',
    owner_id: 60,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax61',
    budget_name: 'Software subscription',
    owner_id: 61,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax62',
    budget_name: 'Software subscription',
    owner_id: 62,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax63',
    budget_name: 'Software subscription',
    owner_id: 63,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax64',
    budget_name: 'Software subscription',
    owner_id: 64,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax65',
    budget_name: 'Software subscription',
    owner_id: 65,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax66',
    budget_name: 'Software subscription',
    owner_id: 66,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax67',
    budget_name: 'Software subscription',
    owner_id: 67,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax68',
    budget_name: 'Software subscription',
    owner_id: 68,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax69',
    budget_name: 'Software subscription',
    owner_id: 69,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax70',
    budget_name: 'Software subscription',
    owner_id: 70,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax71',
    budget_name: 'Software subscription',
    owner_id: 71,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax72',
    budget_name: 'Software subscription',
    owner_id: 72,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax73',
    budget_name: 'Software subscription',
    owner_id: 73,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax74',
    budget_name: 'Software subscription',
    owner_id: 74,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax75',
    budget_name: 'Software subscription',
    owner_id: 75,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax76',
    budget_name: 'Software subscription',
    owner_id: 76,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax77',
    budget_name: 'Software subscription',
    owner_id: 77,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax78',
    budget_name: 'Software subscription',
    owner_id: 78,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
   card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax79',
    budget_name: 'Software subscription',
    owner_id: 79,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax80',
    budget_name: 'Software subscription',
    owner_id: 80,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax81',
    budget_name: 'Software subscription',
    owner_id: 81,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax82',
    budget_name: 'Software subscription',
    owner_id: 82,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax83',
    budget_name: 'Software subscription',
    owner_id: 83,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax84',
    budget_name: 'Software subscription',
    owner_id: 84,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax85',
    budget_name: 'Software subscription',
    owner_id: 85,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax86',
    budget_name: 'Software subscription',
    owner_id: 86,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax87',
    budget_name: 'Software subscription',
    owner_id: 87,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax88',
    budget_name: 'Software subscription',
    owner_id: 88,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax89',
    budget_name: 'Software subscription',
    owner_id: 89,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax90',
    budget_name: 'Software subscription',
    owner_id: 90,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax91',
    budget_name: 'Software subscription',
    owner_id: 91,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax92',
    budget_name: 'Software subscription',
    owner_id: 92,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax93',
    budget_name: 'Software subscription',
    owner_id: 93,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax94',
    budget_name: 'Software subscription',
    owner_id: 94,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax95',
    budget_name: 'Software subscription',
    owner_id: 95,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax96',
    budget_name: 'Software subscription',
    owner_id: 96,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax97',
    budget_name: 'Software subscription',
    owner_id: 97,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax98',
    budget_name: 'Software subscription',
    owner_id: 98,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'burner',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  },
  {
    name: 'Mixmax99',
    budget_name: 'Software subscription',
    owner_id: 99,
    spent: { value: 100, currency: 'SGD' },
    available_to_spend: { value: 1000, currency: 'SGD' },
    card_type: 'subscription',
    expiry: '9 feb',
    limit: 100,
    status: 'active'
  }
]